name: Trigger Azure DevOps Pipeline

on:
  pull_request:
    branches:
      - main  # Adjust this to the branch you want to monitor for PRs

jobs:
  trigger-pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Check Pipeline Result
        run: |
            echo "$(az pipelines build list --organization https://dev.azure.com/prathambande --project Playground)"
            exit 1
